shopsite/cart/urls.py
from django.urls import path
from .views import cart_add,cart_detail,cart_remove

app_name = 'cart'

urlpatterns = [
    path('add/<int:product_id>/',cart_add,name='cart_add'),
    path("",cart_detail,name="cart_detail"),
    path("remove/<int:product_id>/",cart_remove,name='remove_item')
]

shopsite/orders/urls.py
from django.urls import path
from .views import order_confirmation,order_create

app_name = 'orders'

urlpatterns = [
    path('create',order_create,name='order_create'),
    path("confirmation/<int:order_id>/",order_confirmation,name='order_confirmation')
]

shopsite/product/urls.py
from django.urls import path
from . import views

app_name = 'product'

urlpatterns = [
    path('',views.product_list,name='product_list'),
    path('<slug:category_slug>/',views.product_list,name='product_list_by_category'),
    path('product/<int:id>/<slug:slug>/',views.product_detail,name='product_detail')
]

shopsite/shopsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/',include('cart.urls')),
    path('orders/',include('orders.urls')),
    path('',include('product.urls',namespace='product')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shopsite/cart/models.py
from django.db import models
from product.models import product

# Create your models here.

class Cart(models.Model):
    created_at = models.DateTimeField(auto_now_add = True)

    def get_total_price(self):
       try:
        return sum(item.get_total_price() for item in self.items.all())
       except Exception as e:
        # Handle the error and provide a user-friendly error message
        print(f"An error occurred: {e}")
        return 0  # or some other default value

class Item(models.Model):
    cart = models.ForeignKey(Cart,related_name='items',on_delete=models.CASCADE)
    product = models.ForeignKey(product,related_name='cart_product',on_delete=models.CASCADE)
    quantity = models.PositiveBigIntegerField(default=1)

    def get_total_price(self):
        return self.product.price * self.quantity

shopsite/orders/models.py
from django.db import models
from product.models import product

# Create your models here.

class Order(models.Model):
    full_name = models.CharField(max_length=250)
    email= models.EmailField()
    address = models.CharField(max_length=250)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())

class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(product,related_name='order_item', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def get_cost(self):
        return self.price * self.quantity

shopsite/product/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=250)
    slug = models.SlugField(unique = True)

    class Meta:
        verbose_name_plural = "categories"

    def __str__(self):
        return self.name

class product(models.Model):
    category = models.ForeignKey(Category,related_name='product', on_delete=models.CASCADE)
    name = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add = True)
    updated = models.DateTimeField(auto_now = True)
    image = models.ImageField(upload_to='product',blank=True, null=True)

    def __str__(self) -> str:
        return self.name

    def get_absolute_url(self):
        return reverse('product:product_detail', Kwargs={'id': self.id,'slug':self.slug})

shopsite/orders/forms.py
from django import forms
from .models import Order

class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ["full_name","email","address"]

shopsite/cart/views.py
from django.shortcuts import render,get_object_or_404,redirect
from product.models import product
from .models import Cart,Item
from django.views.decorators.http import require_POST
from django.http import JsonResponse
# Create your views here.

@require_POST
def cart_add(request, product_id):
    cart_id = request.session.get('cart_id')

    if cart_id:
        cart = Cart.objects.get(id=cart_id)
    else:
        cart = Cart.objects.create()
        print("Cart created:", cart.id)
        request.session['cart_id'] = cart.id
        print("Cart ID set in session:", request.session['cart_id'])
    
    Product = get_object_or_404(product,id=product_id)

    cart_item, created = Item.objects.get_or_create(cart=cart, product=Product)

    if not created:
        cart_item.quantity += 1

    cart_item.save()

    response_data = {
        "success":True,
        "message":f'Added {Product.name} to cart'
    }
    
    return JsonResponse(response_data)

def cart_detail(request):
    cart_id = request.session.get('cart_id')
    print("Cart ID:", cart_id)

    if cart_id is None:
        print("Cart ID is not set in the session")

    cart = None

    if cart_id:
        try:
            cart = Cart.objects.get(id=cart_id)
            print("Cart:", cart)
        except Cart.DoesNotExist:
            cart = None
            print("Cart does not exist")

    return render(request, 'cart/detail.html', {"cart": cart})

def cart_remove(request,product_id):
    cart_id = request.session.get('cart_id')
    cart = get_object_or_404(Cart,id=cart_id)
    item = get_object_or_404(Item,id=product_id,cart=cart)
    item.delete()

    return redirect("cart:cart_detail")

shopsite/orders/views.py
from django.shortcuts import render,redirect,get_object_or_404
from cart.models import Cart
from .forms import OrderCreateForm
from .models import OrderItem,Order

# Create your views here.

def order_create(request):
    cart=None
    cart_id = request.session.get('cart_id')

    if cart_id:
        cart=Cart.objects.get(id=cart_id)

        if not cart or not cart.items.exists():
            return redirect("cart:cart_detail")
        
    if request.method == "POST":
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            order.save()

            for item in cart.items.all():
                OrderItem.objects.create(
                    order=order,
                    product = item.product,
                    price = item.product.price,
                    quantity = item.quantity,
                )
            cart.delete()
            del request.session["cart_id"]
            return redirect ("orders:order_confirmation",order.id)
        else:
            form =  OrderCreateForm()

        return render(request,"orders/order_create.html", {
            "cart":cart, "form":form
        })

def order_confirmation(request, order_id):
    order = get_object_or_404(Order,id = order_id)
    return render(request, "orders/order_confirmation.html", {"order":order})

shopsite/product/views.py
from django.shortcuts import render,get_object_or_404
from .models import Category,product

# Create your views here.

def product_list(request, category_slug=None):
    category = None
    products = product.objects.filter(available=True)
    categories = Category.objects.all()

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)

    return render(request, 'product/products/list.html', {
        'category':category,
        'product':products,
        'categories':categories,
    })

def product_detail(request,id ,slug):
    products = get_object_or_404(product , id=id , slug=slug , available=True)
    return render(request,'product/products/detail.html',{'product':products})

shopsite/cart/templates/cart/detail.html
{% extends "base.html" %}

{% block title %}My Cart{% endblock %}

{% block content %}
  <h2 class="text-2xl font-bold mb-4">My Cart:</h2>
  {% if cart %}
    <table class="table-auto w-full mb-4">
      <thead>
        <tr class="bg-gray-200 border bottom-2">
          <th class="px-4 py-2">Product</th>
          <th class="px-4 py-2">Quantity</th>
          <th class="px-4 py-2">Price</th>
          <th class="px-4 py-2">Total</th>
          <th class="px-4 py-2">Delete</th>
        </tr>
      </thead>
      <tbody>
        {% for item in cart.items.all %}
          <tr class="hover:bg-gray-100  border bottom-2">
            <td class="px-4 py-2"><a href="{% url 'product:product_detail' item.product.id item.product.slug %}">{{ item.product.name }}</a></td>
            <td class="px-4 py-2">{{ item.quantity }}</td>
            <td class="px-4 py-2">{{ item.product.price }}</td>
            <td class="px-4 py-2">{{ item.get_total_price }}</td>
            <td class="px-4 py-2">
                <form action="{% url 'cart:remove_item' item.id%}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="bg-red-600 text-white px-4 py-1 rounded">Delete</button>
                </form>
            </td>
          </tr>
        {% endfor %}
      </tbody>
      <tfoot>
        <tr class="bg-gray-200  border bottom-2">
          <td colspan="4" class="px-4 py-2">Total:</td>
          <td class="px-4 py-2">{{ cart.get_total_price }} MAD</td>
        </tr>
      </tfoot>
    </table>
  {% else %}
    <p class="text-gray-600">Your cart is empty.</p>
  {% endif %}
  <form action="{% url 'orders:order_create' %}" method="post">
    {% csrf_token %}
    <button type="submit" class="bg-emerald-600 rounded font-bold text-xl p-4 text-slate-50 transition-all hover:bg-emerald-600 hover:bg-opacity-50 hover:text-emerald-600">Proceed To Checkout</button>
  </form>
{% endblock %}

shopsite/orders/templates/orders/order_confirmation.html
{% extends "base.html" %}

{% block title %}Order Confirmation{% endblock %}

{% block content %}
<div class="max-w-2xl mx-auto mt-10 p-8 bg-white shadow-md rounded">
    <h2 class="text-2xl font-bold text-center mb-6 text-emerald-600">Your order has been placed successfully!</h2>
    
    <h3 class="text-xl font-semibold mb-4 text-gray-800">Order ID: <span class="text-emerald-600">#{{ order.id }}</span></h3>
    
    <ul class="mb-6 space-y-4">
        {% for item in order.items.all %}
        <li class="flex justify-between items-center p-4 bg-gray-100 rounded-lg">
            <div>
                <strong class="text-lg font-medium">{{ item.quantity }} x {{ item.product.name }}</strong>
                <br>
                <span class="text-gray-500">{{ item.price }} MAD</span>
            </div>
        </li>
        {% endfor %}
    </ul>

    <p class="text-xl font-bold text-right text-gray-800">Total: <span class="text-emerald-600">{{ order.get_total_cost }} MAD</span></p>
</div>
{% endblock %}

shopsite/orders/templates/orders/order_create.html
{% extends "base.html" %}

{% block title %}Order Creation{% endblock %}

{% block content %}
<div class="max-w-lg mx-auto mt-10 p-6 bg-white shadow-lg rounded-lg">
    <h2 class="text-2xl font-bold mb-6 text-center text-emerald-600">Create Order</h2>
    <form method="post">
        {% csrf_token %}
        <div class="space-y-4">
            {{form.as_p}}
        </div>
        <button type="submit" class="bg-emerald-600 rounded font-bold text-lg p-4 text-slate-50 transition-all hover:bg-emerald-600 hover:bg-opacity-50 hover:text-emerald-600">
            Place Order
        </button>
    </form>
</div>

<style>
    form {
        max-width: 600px;
        margin: 40px auto;
        padding: 20px;
        background-color: #fff;
        border-radius: 8px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    }

    form p {
        font-size: 24px;
        font-weight: bold;
        margin-bottom: 20px;
    }

    form form {
        display: flex;
        flex-direction: column;
        gap: 15px;
    }

    form input{
        padding: 12px;
        font-size: 16px;
        border-radius: 4px;
        border: 1px solid #ccc;
        width: 100%;
    }

    form input:focus {
        outline: none;
        border-color: #52a44d;
    }
</style>
{% endblock %}

shopsite/product/templates/product/products/detail.html
{% extends "base.html" %}

{%block title%}{{product.name}}{%endblock%}

{%block content%}
<div class="container mx-auto p-4 flex justify-center">
    <div class="bg-white shadow-lg rounded-lg p-6 max-w-3xl grid gap-6 lg:grid-cols-2">
        <div class="flex justify-center items-center">
        {% if product.image %}
          <img src="{{product.image.url}}" alt="{{product.name}}" class="max-h-[80vh]">
        {% else %}
          <p class="text-red-600 font-semibold">The image is not available !</p>
        {% endif %} 
        </div>
        <div class="space-y-4 mt-12">
           <h3 class="text-3xl font-semibold">{{product.name}}</h3>
           <p class="text-lg">{{product.description}}</p>
           <p class="text-xl font-bold">{{product.price}} MAD</p>
           <form action="{% url 'cart:cart_add' product.id %}" method="post" id="add_form" class="space-y-2">
              {% csrf_token %}
              <button type="submit" class="bg-emerald-600 rounded font-bold text-xl w-44 p-4 text-slate-50 transition-all hover:bg-emerald-600 hover:bg-opacity-50 hover:text-emerald-600">Add to cart</button>
              <p id="message"  class="text-green-600 text-xl"></p>
           </form>
        </div>
    </div>
</div>

<script>
    document.getElementById('add_form').addEventListener("submit",function(event){
        event.preventDefault();
        const form = event.target;
        const url = form.action;
        const formData = new FormData(form);

        fetch(url,{
            method: 'POST',
            headers: {
                'X-CSRFToken': formData.get('csrfmiddlewaretoken')
            },
            body:formData
        })
        .then(response => response.json())
        .then(data =>{
            messageElement = document.getElementById('message');
            if(data.success){
                messageElement.textContent = data.message;
            }else{
                message.textContent = "Failed to add to cart";
            }
        })
        .catch(error => {
            console.error("Error", error);
        })
    })
</script>
{%endblock%}

shopsite/product/templates/product/products/list.html
{% extends "base.html" %}

{%block title%}Shopping Website{%endblock%}

{%block content%}
<div class="container mx-auto p-4 flex lg:flex-row flex-col">
    <aside class="w-full lg:w-1/4 p-4">
        <h2 class="font-bold text-3xl mb-2">Categories :</h2>
        <ul>
            {% for category in categories %}
            <li class="mb-2">
                <a href="{% url 'product:product_list_by_category' category.slug %}" class="hover:text-emerald-600 lg:hover:font-bold lg:hover:text-2xl text-xl transition duration-200">{{category.name}}</a>
            </li>
            {% endfor %}
        </ul>
    </aside>
    <main class="w-full lg:w-3/4 p-4">
        {% if category%}
        <h2 class="font-bold text-3xl mb-4">{{category.name}}</h2>
        {% else %}
        <h2 class="font-bold text-3xl mb-4">All Products :</h2>
        {% endif %}
        <div class="grid lg:grid-cols-3 grid-flow-col-1 md:grid-cols-2 gap-4">
            {% for product in product %}
            <a href="{% url 'product:product_detail' product.id product.slug %}" class="hover:scale-105 transform transition">
            <div class="shadow-lg rounded-lg border border-black p-4 hover:bg-gray-100 transition duration-300">
                {% if product.image %}
                <img src="{{product.image.url}}" alt="{{product.name}}" class="h-64 w-42 object-cover">
                {% else %}
                <p class="text-red-600 font-semibold">The image is not available !</p>
                {% endif %}
                <h3 class="text-lg font-semibold">{{product.name}}</h3>
                <p class="">{{product.description}}</p>
                <p class="text-xl font-bold">{{product.price}} MAD</p>
            </div>
            </a>
            {% endfor %}
        </div>
    </main>
</div>
{%endblock%}

shopsite/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>{%block title%}E-commerce Website{%endblock%}</title>
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <meta name="description" content="" />
  <link rel="icon" href="favicon.png">
  {% load static %}
  <link href="{% static 'dist/styles.css' %}" rel="stylesheet"/>
</head>
<body class="bg-slate-50 text-gray-600 flex flex-col min-h-screen">
  <header class="shadow-md">
    {% include "includes/navbar.html" %}
  </header>
  <main class="container mx-auto p-8 flex-grow">
    {%block content%}{%endblock%}
  </main>
  <footer class="shadow-md">
    <div class="container mx-auto p-5 text-center">
      <p>@2024 EShop inc. All rights reserved.</p>
    </div>
  </footer>
</body>
</html>

shopsite/templates/includes/navbar.html
<nav class="container mx-auto p-6 flex justify-between items-center">
    <a href="/" class="text-4xl font-bold text-emerald-600">EShop</a>
    <a href="{% url 'cart:cart_detail' %}">
        <svg class="w-8" version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 width="40px" height="36px" viewBox="0 0 40 36" style="enable-background:new 0 0 40 36;" xml:space="preserve">
<g id="Page-1_4_" sketch:type="MSPage">
	<g id="Desktop_4_" transform="translate(-84.000000, -410.000000)" sketch:type="MSArtboardGroup">
		<path id="Cart" sketch:type="MSShapeGroup" class="st0" d="M94.5,434.6h24.8l4.7-15.7H92.2l-1.3-8.9H84v4.8h3.1l3.7,27.8h0.1
			c0,1.9,1.8,3.4,3.9,3.4c2.2,0,3.9-1.5,3.9-3.4h12.8c0,1.9,1.8,3.4,3.9,3.4c2.2,0,3.9-1.5,3.9-3.4h1.7v-3.9l-25.8-0.1L94.5,434.6"
			/>
	</g>
</g>
  </svg>
    </a>
</nav>